# Generated by Django 3.1 on 2021-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxypay', '0005_auto_20210108_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='key',
            field=models.CharField(default=None, editable=False, max_length=125, null=True, unique=True),
        ),
    ]
