# Generated by Django 3.2 on 2021-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxypay', '0007_auto_20210422_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.AlterField(
            model_name='reference',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='data',
            field=models.JSONField(default=dict, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='fields',
            field=models.JSONField(default=dict, verbose_name='reference data fields'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='payment',
            field=models.JSONField(default=None, null=True, verbose_name='payment data from proxypay'),
        ),
    ]
